### ISSUE TITLE
Installed Auroraplus sucessfully via HACS but will not install as an integration  

### ISSUE THREAD

**Issue by Katabatic1970** [LeighCurran/AuroraPlusHA#2]
I have an Aurora+ account and was stoked when I found your integration however I Installed Auroraplus sucessfully via HACS but will not install as an integration in my Home assistant - error logs are below:

Logger: homeassistant.components.sensor
Source: custom_components/auroraplus/sensor.py:122
Integration: Sensor (documentation, issues)
First occurred: August 20, 2021, 11:36:23 PM (2 occurrences)
Last logged: August 20, 2021, 11:36:23 PM

auroraplus: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 646, in async_device_update
    await task
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/auroraplus/sensor.py", line 122, in update
    self._session.getsummary()
  File "/usr/local/lib/python3.9/site-packages/auroraplus/__init__.py", line 78, in getsummary
    summarydata = self.request("day")
  File "/usr/local/lib/python3.9/site-packages/auroraplus/__init__.py", line 69, in request
    request = self.session.get(self.url + '/usage/' + timespan +'?serviceAgreementID=' + self.serviceAgreementID + '&customerId=' + self.customerId + '&index=-1', headers={'Authorization': self.token})
AttributeError: 'api' object has no attribute 'serviceAgreementID'

**Comment by david-holbrook** [comment]
Hi @Katabatic1970,

I had the same issue and was able to resolve it with the following install process:

1) install the Aurora+ integration via HACS - but don't add your Aurora+ config to configuration.yaml at this stage.

2) restart Home Assistant - this will allow the integration to load the new sensors and beginning pulling down the PYPi library dependency. This only takes a minute or two the first time the new integration is loaded.

3) Now add your Aurora+ config into configuration.yaml and restart again.

Give this a shot and see you you go...

**Comment by Katabatic1970** [comment]
Hi @david-holbrook,
Many thanks for the guidance, your solution has resolved all the issues identified previously in the logs, which is great.
I'm still a little stumped though. Normally after integration or custom_component is installed with HACS I'd head over to Configuration > Integrations, type the name of the new Custom Component, and follow the configuration wizard. however in this instance, this doesn't seem to be occurring. Am I missing something or is this another trick?
TIA,
Eddie

**Comment by LeighCurran** [comment]
Hey mate,

It doesn't have front end configuration yet (Not all Home Assistant integration support it). You can configure Aurora+ via your configuration.yaml file (https://www.home-assistant.io/docs/configuration/) with the following:

```yaml
sensor:
  - platform: auroraplus
    username: _username@email.com_
    password: _Password_
```

If you already have a sensor section just add the platform, username and password under it for example:

```yaml
sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'time_date'
      
  - platform: auroraplus
    username: _username@email.com_
    password: _Password_
```

Let us know how you go,

Cheers Leigh.

**Comment by Katabatic1970** [comment]
Hi @LeighCurran, 
Well, I've added the relevant lines including my username and password to my _configuration.yaml_,I restarted the server, the logs indicated the auroraplus integration was starting and then......the integration fails....logs are below

Logger: homeassistant.components.sensor
Source: custom_components/auroraplus/sensor.py:120
Integration: Sensor (documentation, issues)
First occurred: 10:25:00 PM (3 occurrences)
Last logged: 10:25:02 PM

auroraplus: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 646, in async_device_update
    await task
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/auroraplus/sensor.py", line 120, in update
    self._session.getcurrent()
  File "/usr/local/lib/python3.9/site-packages/auroraplus/__init__.py", line 111, in getcurrent
    self.AmountOwed = "{:.2f}".format(premise['AmountOwed'])
TypeError: unsupported format string passed to NoneType.__format__


Any guidance you may have would be much appreciated

Cheers,
Eddie
