### ISSUE TITLE
Does this work with the new Energy update?

### ISSUE THREAD

**Issue by nukolator** [LeighCurran/AuroraPlusHA#3]
I've managed to get the data coming into HA, but I can't figure out how to have it feed to Energy.  I'll report back if I figure it out, but open to any assistance!

**Comment by LeighCurran** [comment]
Hey,

It doesn't support it yet (I wrote it the week before the energy update). I just pushed a new version of the sensor.py to the dev branch with what 'should' get it working based on the doco here: https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics

However I still can't select it in the energy section of my HA instance. Give it a go, you should see a new attribute on kilowatthourusage called state_class: measurement.

Let me know if it works for you.

Regards,

Leigh.

**Comment by LeighCurran** [comment]
@david-holbrook

**Comment by LeighCurran** [comment]
The integration now supports long term statistics which technically means you can use it in the energy dashboard however it doesn't really make sense to as the Aurora+ data is only updated daily.

**Comment by LeighCurran** [comment]
The integration supports long term statistics now so technically you can use it in the energy dashboard however it doesn't really make sense to as the Aurora+ data is only updated daily.
