### ISSUE TITLE
AuroraPlus module

### ISSUE THREAD

**Issue by alexdlm** [LeighCurran/AuroraPlusHA#4]
Hey @LeighCurran, thanks for this integration I was about to write my own and found this. It's a great start for what I'm wanting to achieve.

I can't see your AuroraPlus python module, is it a private repo or has it been taken down?

**Comment by LeighCurran** [comment]
It's a private repo, what features are you looking for?

**Comment by alexdlm** [comment]
From the API side, per-tariff kW/$ and historical/comparison values. And I'd like to get better clarity around time, ie the API returns values for yesterday, so from the hassio side I'd like to record that more accurately (which probably means direct DB inserts rather than sensor state updates from what I've seen so far, but I haven't dug too deep)

**Comment by LeighCurran** [comment]
Hey man, I added you to the repo for the Pypi package. From memory the AuroraPlus API only updated daily, even the hourly data so I stuck with just pulling summary totals and account info.
