### ISSUE TITLE
Data from specific dates in auroraplus?

### ISSUE THREAD

**Issue by BuongiornoTexas** [LeighCurran/AuroraPlusHA#5]
HI @LeighCurran  - I'm trying to use your auroraplus module to pull data from specific dates in the aurora+ history. Can you advise how I should modify the call to requests to do something like get the data for 05/01/2023? (or if not, do you have any recommendations for a tool I can use to intercept the REST api calls so that I can figure it out myself?)

Thanks, 

BT

**Comment by LeighCurran** [comment]
Hey mate, the AuroraPlus data only updated daily when I wrote the Pypi package. Looks like I added the ability to pull some historical data which might help: https://pypi.org/project/auroraplus/

**Comment by BuongiornoTexas** [comment]
Thanks Leigh - appreciated.
